In [28]:
import pyvista as pv
mesh = pv.read("BronchialTree.obj")
print(mesh.points)
point = [0.1, 0.2, 0.3]
index = mesh.find_closest_cell(point)
index

[[  35.8555   93.6012 1194.74  ]
 [ -16.7894   95.8828 1194.48  ]
 [  35.8512   93.6082 1194.78  ]
 ...
 [  14.0563  161.424  1428.38  ]
 [  14.5352  161.401  1428.37  ]
 [  15.1151  161.318  1428.26  ]]


32

In [29]:
import numpy as np
lines = []
directions = []
with open('rename5.txt') as f:
    lines = f.read().splitlines()
for i in range(len(lines)):
    lines[i] = [float(a) for a in lines[i].split()]
positives = []
for l in lines:
    positives.append(l[0:3])
    directions.append(l[3:])
d = directions
directions = [[x[0] * 100, x[1] * 100, x[2] * 100] for x in directions]
directions = np.array(directions)
positives = np.array(positives)
directions = np.add(positives, directions)

In [30]:
import open3d as o3d

pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(positives)
pcd.paint_uniform_color([1, 0.706, 0])

o3d.visualization.draw_geometries([pcd])

In [4]:
pcd.voxel_down_sample(voxel_size=4.65175)

PointCloud with 475 points.

In [31]:
import open3d as o3d
cloud = np.stack(np.array(mesh.points))
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(cloud)
downpcd = pcd.voxel_down_sample(voxel_size=4.65175)
p_cloud = np.asarray(downpcd.points)
data_cloud = []
labels = []
for i in range(len(positives)):
    data_cloud.append(p_cloud)

In [6]:
import open3d as o3d

pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(data_cloud[0])
pcd.paint_uniform_color([1, 0.706, 0])

o3d.visualization.draw_geometries([pcd])

In [32]:
import numpy as np

def unit_vector(vector):
    """ Returns the unit vector of the vector.  """
    return vector / np.linalg.norm(vector)

def angle_between(v1, v2):
    """ Returns the angle in radians between vectors 'v1' and 'v2'::

            >>> angle_between((1, 0, 0), (0, 1, 0))
            1.5707963267948966
            >>> angle_between((1, 0, 0), (1, 0, 0))
            0.0
            >>> angle_between((1, 0, 0), (-1, 0, 0))
            3.141592653589793
    """
    v1_u = unit_vector(v1)
    v2_u = unit_vector(v2)
    return np.arccos(np.clip(np.dot(v1_u, v2_u), -1.0, 1.0))
angle_between([0,1, 19199], [1, 0, 4])


0.24497866855277678

In [33]:
import math
import pyvista
points = []
pos = []
neg = []
counter = 0
for i in range(2000):
    index = mesh.find_closest_cell(positives[i])
    normal = mesh.cell_normals[index]
    normal = [-normal[0], -normal[1], -normal[2]]
    normal = np.add(mesh.cell_centers().points[index], normal)
    d[i] = [-d[i][0], -d[i][1], -d[i][2]]
    if angle_between(normal, d[i]) < math.pi/4:
        pos.append(mesh.cell_centers().points[index])
    else:
        neg.append(mesh.cell_centers().points[index])
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

1862
1863
1864
1865
1866
1867
1868
1869
1870
1871
1872
1873
1874
1875
1876
1877
1878
1879
1880
1881
1882
1883
1884
1885
1886
1887
1888
1889
1890
1891
1892
1893
1894
1895
1896
1897
1898
1899
1900
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999


In [34]:
import math
def closest_point(target, points):
    c_point = []
    d = 100000
    for i in points:
        if math.dist(target, i) < d:
            d = math.dist(target, i)
            c_point = i
    return c_point
new_neg = []
for j in neg:
    if math.dist(closest_point(j, pos), j) > 2:
        new_neg.append(j)
len(new_neg)
neg = new_neg

In [10]:
import open3d as o3d

pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(pos)
pcd.paint_uniform_color([0, 0.706, 0])

pcd2 = o3d.geometry.PointCloud()
pcd2.points = o3d.utility.Vector3dVector(neg)
pcd2.paint_uniform_color([0.5, 0, 0])

o3d.visualization.draw_geometries([pcd, pcd2])

In [35]:
import random
pos = np.stack(pos)
neg = np.stack(neg)
hash = {}
array = []
for i in pos:
    array.append([i, 1])
for i in neg:
    array.append([i, 0])
random.shuffle(array)
points = []
labels = []
for i in array:
    points.append(i[0])
    labels.append(i[1])
points = np.stack(points)

In [36]:
import open3d as o3d

pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(pos)
pcd.paint_uniform_color([1, 0.706, 0])

pcd2 = o3d.geometry.PointCloud()
pcd2.points = o3d.utility.Vector3dVector(neg)
pcd2.paint_uniform_color([0.5, 0, 0])

o3d.visualization.draw_geometries([pcd, pcd2])

In [37]:
import tensorflow as tf
def augment(points):
    # jitter points
    # shuffle points
    points = tf.random.shuffle(points)
    return points
for i in range(len(data_cloud)):
    data_cloud[i] = augment(data_cloud[i])

In [38]:
def conv_bn(x, filters):
    x = layers.Conv1D(filters, kernel_size=1, padding="valid")(x)
    x = layers.BatchNormalization(momentum=0.0)(x)
    return layers.Activation("relu")(x)
def dense_bn(x, filters):
    x = layers.Dense(filters,kernel_initializer='ones',
    kernel_regularizer=tf.keras.regularizers.L1(0.1),
    activity_regularizer=tf.keras.regularizers.L2(0.1))(x)
    x = layers.BatchNormalization(momentum=0.0)(x)
    return layers.Activation("relu")(x)
def dense_bn2(x, filters):
    x = layers.Dense(filters)(x)
    x = layers.BatchNormalization(momentum=0.0)(x)
    return layers.Activation("relu")(x)

In [39]:
import keras
class OrthogonalRegularizer(keras.regularizers.Regularizer):
    def __init__(self, num_features, l2reg=0.001):
        self.num_features = num_features
        self.l2reg = l2reg
        self.eye = tf.eye(num_features)

    def __call__(self, x):
        x = tf.reshape(x, (-1, self.num_features, self.num_features))
        xxt = tf.tensordot(x, x, axes=(2, 2))
        xxt = tf.reshape(xxt, (-1, self.num_features, self.num_features))
        return tf.reduce_sum(self.l2reg * tf.square(xxt - self.eye))

In [40]:
def tnet(inputs, num_features):

    bias = keras.initializers.Constant(np.eye(num_features).flatten())
    reg = OrthogonalRegularizer(num_features)

    x = conv_bn(inputs, 32)
    x = conv_bn(x, 64)
    x = conv_bn(x, 512)
    x = layers.GlobalMaxPooling1D()(x)
    x = dense_bn(x, 256)
    x = dense_bn(x, 128)
    x = layers.Dense(
        num_features * num_features,
        kernel_initializer="zeros",
        bias_initializer=bias,
        activity_regularizer=reg,
    )(x)
    feat_T = layers.Reshape((num_features, num_features))(x)
    return layers.Dot(axes=(2, 1))([inputs, feat_T])

In [41]:
from keras.models import Sequential
from keras.layers import Concatenate
from keras.layers import Activation
from keras.layers import Dense
from keras.layers import Dropout
from keras import layers
inputs = keras.Input(shape=(2048, 3))
x = tnet(inputs, 3)
x = conv_bn(x, 32)
x = conv_bn(x, 32)
x = tnet(x, 32)
x = conv_bn(x, 32)
x = conv_bn(x, 64)
x = conv_bn(x, 512)
x = layers.GlobalMaxPooling1D()(x)
x = dense_bn(x, 256)
x = layers.Dropout(0.3)(x)
x = dense_bn(x, 1)

a_input = keras.Input(shape=(1, 3))
a = layers.GlobalMaxPooling1D()(a_input)
a = dense_bn2(a, 256)
a = dense_bn2(a, 128)
mergedOutput = Concatenate()([a,x])
out = dense_bn2(mergedOutput,128)
out = Dense(2, activation='softmax')(out)



model = keras.Model(inputs=[inputs, a_input], outputs=out, name="pointnet")
model.summary()

Model: "pointnet"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_5 (InputLayer)           [(None, 2048, 3)]    0           []                               
                                                                                                  
 conv1d_22 (Conv1D)             (None, 2048, 32)     128         ['input_5[0][0]']                
                                                                                                  
 batch_normalization_40 (BatchN  (None, 2048, 32)    128         ['conv1d_22[0][0]']              
 ormalization)                                                                                    
                                                                                                  
 activation_40 (Activation)     (None, 2048, 32)     0           ['batch_normalization_40[0

 activation_49 (Activation)     (None, 2048, 512)    0           ['batch_normalization_49[0][0]'] 
                                                                                                  
 global_max_pooling1d_9 (Global  (None, 512)         0           ['activation_49[0][0]']          
 MaxPooling1D)                                                                                    
                                                                                                  
 dense_27 (Dense)               (None, 256)          131328      ['global_max_pooling1d_9[0][0]'] 
                                                                                                  
 batch_normalization_50 (BatchN  (None, 256)         1024        ['dense_27[0][0]']               
 ormalization)                                                                                    
                                                                                                  
 activatio

 activation_56 (Activation)     (None, 1)            0           ['batch_normalization_56[0][0]'] 
                                                                                                  
 concatenate_2 (Concatenate)    (None, 129)          0           ['activation_58[0][0]',          
                                                                  'activation_56[0][0]']          
                                                                                                  
 dense_34 (Dense)               (None, 128)          16640       ['concatenate_2[0][0]']          
                                                                                                  
 batch_normalization_59 (BatchN  (None, 128)         512         ['dense_34[0][0]']               
 ormalization)                                                                                    
                                                                                                  
 activatio

In [42]:
points = np.expand_dims(points, axis=1)

In [43]:
import numpy
labels = numpy.asarray(labels)
data_cloud = numpy.asarray(data_cloud)

In [44]:
from tensorflow import keras
from sklearn.model_selection import KFold, cross_val_score
k_fold = KFold(n_splits=5)
for train_indices, test_indices in k_fold.split(labels):
    model.compile(
    loss="sparse_categorical_crossentropy",
    optimizer=keras.optimizers.Adam(learning_rate=0.01),
    metrics=["sparse_categorical_accuracy"],
)
    print('Train: %s | test: %s' % (labels[train_indices], labels[test_indices]))
    labels_train = labels[train_indices]
    data_cloud_train = data_cloud[train_indices]
    points_train = points[train_indices]
    
    labels_test = labels[test_indices]
    data_cloud_test = data_cloud[test_indices]
    points_test = points[test_indices]
    
    labels_test = tf.convert_to_tensor(labels_test)
    data_cloud_test= tf.convert_to_tensor(data_cloud_test)
    points_test = tf.convert_to_tensor(points_test)
    
    model.fit(x = [data_cloud_train, points_train], y= [labels_train], epochs=5)
    print("test case:")
    preds = model.predict([data_cloud_test, points_test])
    predictions = tf.math.argmax(preds, -1)
    wrong = 0
    labels_test = labels_test.numpy()
    predictions = predictions.numpy()
    for i in range(len(predictions)):
        if(predictions[i] != labels_test[i]):
            wrong+=1
    print(1-(wrong/len(predictions)))
     

Train: [0 1 0 ... 1 0 0] | test: [1 0 0 1 0 0 0 1 0 1 1 1 0 0 0 1 1 0 1 0 0 1 1 1 1 1 0 1 0 0 1 0 0 1 1 1 1
 1 0 1 1 0 0 1 1 1 1 0 0 0 0 0 0 1 1 0 1 1 0 1 0 1 1 1 1 1 0 0 1 0 1 1 1 1
 0 1 0 1 1 0 1 1 1 1 0 1 1 1 1 1 1 1 1 0 0 1 0 0 0 1 0 1 1 1 0 1 0 0 1 1 1
 1 1 1 1 0 0 0 0 1 1 1 0 0 1 0 0 0 1 1 0 0 1 1 1 1 1 0 1 0 0 1 0 0 1 1 0 1
 1 1 1 1 1 0 0 0 1 0 1 0 0 0 1 1 0 1 0 1 0 0 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1
 1 1 0 1 1 1 1 0 0 0 0 0 0 1 1 0 1 0 1 1 0 0 0 1 0 1 1 1 0 0 0 1 1 1 1 0 0
 1 1 0 0 0 1 1 1 1 1 1 1 1 0 1 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 1 1 1 0 1 1 1
 1 1 1 1 1 1 1 1 0 0 0 0 0 1 0 0 0 1 1 0 1 0 0 1 1 1 1 1 0 1 1 1 0 1 0 1 0
 1 0 1 0 0 0 0 1 1 1 1 0 1 1 0 0 1 0 1 1 1 0 1 1 1 1 0 1 1 0 1 0 0 1 1 0 1
 0 0 0 1 1 0 0 1 1 1 0]
Epoch 1/5
43/43 [==============================] - 140s 3s/step - loss: 16289379.0000 - sparse_categorical_accuracy: 0.8378
Epoch 2/5
43/43 [==============================] - 136s 3s/step - loss: 500850.5938 - sparse_categorical_accuracy: 0.8705
Epoch 3/5
43/43 [=====

KeyboardInterrupt: 

In [ ]:
data = test_dataset.take(1)

points, labels = list(data)[0]
points = points[:8, ...]
labels = labels[:8, ...]

preds = model.predict(points)
preds = tf.math.argmax(preds, -1)

points = points.numpy()

fig = plt.figure(figsize=(15, 10))
for i in range(8):
    ax = fig.add_subplot(2, 4, i + 1, projection="3d")
    ax.scatter(points[i, :, 0], points[i, :, 1], points[i, :, 2])
    ax.set_title(
        "pred: {:}, label: {:}".format(
            CLASS_MAP[preds[i].numpy()], CLASS_MAP[labels.numpy()[i]]
        )
    )
    print("prediction: " + CLASS_MAP[preds[i].numpy()])
    print("label: " + CLASS_MAP[labels.numpy()[i]])
    ax.set_axis_off()
plt.show()


In [36]:
len(model.layers)

75

In [11]:
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(coordinates)
o3d.io.write_point_cloud("./data.ply", pcd)



True

In [68]:
import open3d as o3d


pcd = o3d.io.read_point_cloud("data.ply")
print(pcd)

PointCloud with 209634 points.


In [69]:
mesh2 = trimesh.load("data.ply")
mesh2.show()

C:\Users\Nitin\anaconda3\lib\site-packages\IPython\core\display.py:724: UserWarning: Consider using IPython.display.IFrame instead
  warnings.warn("Consider using IPython.display.IFrame instead")


In [ ]:
mesh2.show()

In [70]:
downpcd = pcd.voxel_down_sample(voxel_size=7.409)
print(downpcd)

PointCloud with 2048 points.


In [6]:
o3d.visualization.draw_geometries([downpcd])

In [7]:
from numpy import random

from scipy.spatial import distance
def closest_node(node, nodes):
    closest_index = distance.cdist([node], nodes).argmin()
    return nodes[closest_index]

In [71]:
down_points = np.asarray(downpcd.points)
d = down_points
down_points = np.expand_dims(down_points, axis=0)

In [77]:
for i in range()

array([[208.35475595, 142.30621604, 206.71854074]])

In [61]:
from sklearn.preprocessing import minmax_scale

d = d/d.sum(axis=-1,keepdims=True)


SyntaxError: invalid character '–' (U+2013) (Temp/ipykernel_15608/2564571265.py, line 4)

In [33]:
closest_node([0,0,0], d)

array([0.32362995, 0.33997428, 0.33639577])

In [14]:
distances = downpcd.compute_nearest_neighbor_distance()
avg_dist = np.mean(distances)
radius = 3 * avg_dist
bpa_mesh = o3d.geometry.TriangleMesh.create_from_point_cloud_ball_pivoting(pcd,o3d.utility.DoubleVector([radius, radius * 2]))
dec_mesh = mesh.simplify_quadric_decimation(100000)
o3d.io.write_triangle_mesh(output_path+"bpa_mesh.ply", dec_mesh)


RuntimeError: [Open3D Error] (class std::shared_ptr<class open3d::geometry::TriangleMesh> __cdecl open3d::geometry::BallPivoting::Run(const class std::vector<double,class std::allocator<double> > &)) D:\a\Open3D\Open3D\cpp\open3d\geometry\SurfaceReconstructionBallPivoting.cpp:677: ReconstructBallPivoting requires normals


In [15]:
preds = model.predict(down_points)
preds = tf.math.argmax(preds, -1)


NameError: name 'model' is not defined

In [16]:
print(type(preds[0].numpy()))

NameError: name 'preds' is not defined

In [17]:
print(CLASS_MAP[preds[0].numpy()])

NameError: name 'CLASS_MAP' is not defined

In [18]:


a = random.randint(1000, size=(50000, 2))

some_pt = (1, 2)

closest_node(some_pt, a)

array([3, 3])

In [19]:
lines = []
with open('C:/Users/Nitin/Downloads/rename.txt') as f:
    lines = f.read().splitlines()
for i in range(len(lines)):
    lines[i] = [float(a) for a in lines[i].split()]
positives = []
for l in lines:
    positives.append(l[0:3])
positives = np.array(positives)

In [20]:
positives = positives/positives.sum(axis=-1,keepdims=True)


In [50]:
device = o3d.core.Device("CPU:0")
dtype = o3d.core.float32
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(positives)

In [51]:
o3d.visualization.draw_geometries([pcd])

[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The handle is invalid. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The handle is invalid. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The handle is invalid. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The requested transformation operation is not supported. 
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The requested transformation operation is no

In [29]:
down_points

array([[[0.19987987, 0.21828749, 0.58183264],
        [0.0703259 , 0.09090909, 0.83876501],
        [0.37381129, 0.25531297, 0.37087574],
        ...,
        [0.41726248, 0.2395466 , 0.34319092],
        [0.4091829 , 0.2385146 , 0.3523025 ],
        [0.41308028, 0.23571211, 0.35120761]]])

In [42]:
import math
neg = []
for r in (range(len(d))):
    close = closest_node(d[r], positives)
    if(math.dist(close, d[r])>=0.6):
        neg.append(d[r])


In [53]:
max(positives[0])

0.8832356620807347

In [33]:
model2 = tf.keras.Sequential([
    tf.keras.layers.Flatten(input_shape=(1, 3)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(2, activation='softmax')
])
model2.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])
model2.fit(points_train, labels_train, epochs=100)

Epoch 1/100


C:\Users\Nitin\anaconda3\lib\site-packages\tensorflow\python\util\dispatch.py:1082: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a sigmoid or softmax activation and thus does not represent logits. Was this intended?"
  return dispatch_target(*args, **kwargs)


43/43 [==============================] - 0s 2ms/step - loss: 2.8732 - accuracy: 0.5476
Epoch 2/100
43/43 [==============================] - 0s 2ms/step - loss: 0.7402 - accuracy: 0.7367
Epoch 3/100
43/43 [==============================] - 0s 2ms/step - loss: 0.6617 - accuracy: 0.6865
Epoch 4/100
43/43 [==============================] - 0s 2ms/step - loss: 0.5494 - accuracy: 0.7556
Epoch 5/100
43/43 [==============================] - 0s 2ms/step - loss: 0.5408 - accuracy: 0.7542
Epoch 6/100
43/43 [==============================] - 0s 2ms/step - loss: 0.6071 - accuracy: 0.7360
Epoch 7/100
43/43 [==============================] - 0s 2ms/step - loss: 0.9550 - accuracy: 0.6647
Epoch 8/100
43/43 [==============================] - 0s 2ms/step - loss: 0.7099 - accuracy: 0.7302
Epoch 9/100
43/43 [==============================] - 0s 2ms/step - loss: 0.5676 - accuracy: 0.7615
Epoch 10/100
43/43 [==============================] - 0s 1ms/step - loss: 0.7095 - accuracy: 0.7062
Epoch 11/100
43/43 [=

In [34]:
preds = model2.predict([points_test])
preds

array([[2.78854482e-02, 9.72114563e-01],
       [6.98661268e-01, 3.01338762e-01],
       [1.78043563e-02, 9.82195675e-01],
       [6.69183493e-01, 3.30816507e-01],
       [7.20675945e-01, 2.79324085e-01],
       [9.77541268e-01, 2.24587284e-02],
       [8.67503703e-01, 1.32496357e-01],
       [7.79177129e-01, 2.20822841e-01],
       [9.98886287e-01, 1.11371605e-03],
       [9.74897265e-01, 2.51027383e-02],
       [3.07876796e-01, 6.92123234e-01],
       [9.69945669e-01, 3.00543793e-02],
       [1.45456782e-02, 9.85454321e-01],
       [9.09774423e-01, 9.02255103e-02],
       [2.22569108e-01, 7.77430952e-01],
       [2.50323147e-01, 7.49676824e-01],
       [2.77187228e-02, 9.72281337e-01],
       [8.51966664e-02, 9.14803386e-01],
       [2.90238089e-03, 9.97097611e-01],
       [2.84007490e-02, 9.71599221e-01],
       [8.23845446e-01, 1.76154479e-01],
       [9.02413070e-01, 9.75869074e-02],
       [2.42327247e-03, 9.97576773e-01],
       [9.56881523e-01, 4.31184918e-02],
       [2.523860